### ISSUE TITLE
RuntimeError: CUDA error: initialization error for "CMU Panoptic Dataset"

### ISSUE THREAD

**Issue by Cranjis-McB** [hustvl/4DGaussians#185]
First of all, Great work. I was running the code for CMU Panoptic Dataset but got the CUDA Runtime Error. Upon Debugging I figured out after loading data in [Dataloader here](https://github.com/hustvl/4DGaussians/blob/9e32cb1cfd8dfef9096b09509db2175c1f1a35f3/train.py#L92). It throws up CUDA Runtime Error in [this line](https://github.com/hustvl/4DGaussians/blob/9e32cb1cfd8dfef9096b09509db2175c1f1a35f3/train.py#L94). Attaching the logs below for better understanding. Thanks in advance.

**Logs**:

RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "/home/vikarm/anaconda3/envs/Gaussians4D/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/vikarm/anaconda3/envs/Gaussians4D/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/vikarm/anaconda3/envs/Gaussians4D/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 259, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
  File "/home/vikarm/anaconda3/envs/Gaussians4D/lib/python3.7/site-packages/torch/storage.py", line 800, in _share_cuda_
    return self._storage._share_cuda_(*args, **kwargs)

**Comment by Cranjis-McB** [comment]
I figured out the workaround. Thanks.

**Comment by BruceKnife** [comment]
> I figured out the workaround. Thanks.

Hello！How to solve this problem? I have same problem.

**Comment by Cranjis-McB** [comment]
Hii @BruceKnife  Sorry for late reply. I guess I was getting this error because [readPanopticMeta](https://github.com/hustvl/4DGaussians/blob/9e32cb1cfd8dfef9096b09509db2175c1f1a35f3/scene/dataset_readers.py#L553) loads all the images at once and there was not enough memory to store on GPU. Instead I created a dataset class like the one in [multipleview_dataset.py](https://github.com/hustvl/4DGaussians/blob/master/scene/multipleview_dataset.py#L23) which loads the data on the run.
